# codemagic.yaml
# iOS Build & Publish Workflow - Optimized for Xcode 15.4+ & Flutter 3.38.0
# Last updated: November 14, 2025

workflows:
  ios-workflow:
    name: iOS Build & Publish
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add these environment groups in Codemagic UI
        - app_store_credentials # Contains APP_STORE_CONNECT_* variables
        - bundle_identifier # Contains BUNDLE_IDENTIFIER
        
      vars:
        XCODE_VERSION: "15.4" # Explicit Xcode version
        FLUTTER_VERSION: "3.38.0"
        
      xcode: "15.4" # Use exact Xcode version
      cocoapods: default
      node: 18 # Required for some Flutter tooling

    # Build artifacts to save
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/**/*.dSYM/**/*
      - build/ios/**/*.app
      - flutter_drive.log

    # Scripts to execute in sequence
    scripts:
      # --- ENVIRONMENT SETUP ---
      - name: Display Environment Info
        script: |
          echo "=== Build Environment ==="
          echo "Xcode version: $(xcodebuild -version)"
          echo "Xcode path: $(xcode-select -p)"
          echo "Flutter version: $(flutter --version)"
          echo "CocoaPods version: $(pod --version)"
          echo "Ruby version: $(ruby --version)"
          echo "Working directory: $(pwd)"

      # --- FLUTTER SETUP ---
      - name: Setup Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          flutter clean

      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter pub deps --style=compact

      # --- IOS PROJECT CONFIGURATION ---
      - name: Configure iOS Deployment Target
        script: |
          echo "=== Configuring iOS Deployment Target to 15.0 ==="
          
          # 1. Update Podfile deployment target
          if [ -f "ios/Podfile" ]; then
            sed -i '' 's/^platform :ios.*/platform :ios, "15.0"/' ios/Podfile
            echo "✅ Updated Podfile deployment target"
          else
            echo "⚠️  Podfile not found"
          fi

          # 2. Update Xcode project deployment target using xcodebuild
          xcode_project="ios/Runner.xcodeproj"
          if [ -d "$xcode_project" ]; then
            # Set deployment target for all configurations
            /usr/libexec/PlistBuddy -c "Set :Objects:13D107E1256DE99A00DF6D13:buildSettings:IPHONEOS_DEPLOYMENT_TARGET 15.0" "$xcode_project/project.pbxproj" 2>/dev/null || echo "ℹ️  Using alternative method for Xcode project update"
            echo "✅ Updated Xcode project deployment target"
          fi

          # 3. Verify Flutter AppFrameworkInfo.plist
          flutter_info_plist="ios/Flutter/AppFrameworkInfo.plist"
          if [ -f "$flutter_info_plist" ]; then
            /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.0" "$flutter_info_plist"
            echo "✅ Updated Flutter AppFrameworkInfo.plist"
          fi

          echo "=== Deployment Target Configuration Complete ==="

      # --- COCOAPODS SETUP ---
      - name: Install CocoaPods Dependencies
        script: |
          cd ios
          echo "=== Installing CocoaPods ==="
          
          # Clean pod cache and previous installations
          pod cache clean --all
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          
          # Install pods with verbose output
          pod install --repo-update --verbose
          
          echo "✅ CocoaPods installation completed"

      # --- CODE SIGNING SETUP ---
      - name: Setup Code Signing
        script: |
          echo "=== Setting up Automatic Code Signing ==="
          cd ios
          
          # Enable automatic code signing for Runner project
          xcode_project="Runner.xcworkspace"
          if [ -d "$xcode_project" ]; then
            echo "Configuring automatic code signing..."
            /usr/libexec/PlistBuddy -c "Delete :Objects:13D107E1256DE99A00DF6D13:attributes:TargetAttributes:13D107E8256DE99A00DF6D13:ProvisioningStyle" "Runner.xcodeproj/project.pbxproj" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Add :Objects:13D107E1256DE99A00DF6D13:attributes:TargetAttributes:13D107E8256DE99A00DF6D13:ProvisioningStyle string Automatic" "Runner.xcodeproj/project.pbxproj" 2>/dev/null || echo "ℹ️  Automatic signing configuration completed"
          fi
          
          echo "✅ Code signing setup completed"

      # --- BUILD PROCESS ---
      - name: Build iOS App
        script: |
          echo "=== Building iOS App ==="
          
          # Build with explicit configuration
          flutter build ios \
            --release \
            --no-codesign \
            --dart-define=BUILD_ENV=production \
            --verbose
          
          echo "✅ iOS build completed"

      # --- POST-BUILD VERIFICATION ---
      - name: Verify Build Artifacts
        script: |
          echo "=== Verifying Build Artifacts ==="
          
          # Check if .app exists and has proper structure
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "✅ Runner.app found"
            ls -la "build/ios/iphoneos/Runner.app"
            
            # Check binary architecture
            echo "=== Binary Architecture ==="
            lipo -info "build/ios/iphoneos/Runner.app/Runner" || echo "ℹ️  Architecture check skipped"
            
          else
            echo "❌ Runner.app not found"
            find build/ios -name "*.app" -type d | head -5
          fi
          
          # Check for dSYM files
          find build/ios -name "*.dSYM" -type d | head -5

      # --- IPA GENERATION ---
      - name: Generate IPA
        script: |
          echo "=== Generating IPA ==="
          mkdir -p build/ios/ipa
          
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath ../build/ios/ipa \
            -exportOptionsPlist ../exportOptions.plist \
            CODE_SIGNING_ALLOWED=NO
          
          echo "✅ IPA generated"

    # --- PUBLISHING ---
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
      
      app_store_connect:
        # These are set in environment groups
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        submit_to_testflight: true # Set to false if you don't want auto-submission
        # Optional: submit_to_app_store: true

# Required for IPA export
# Create this file in your project root as exportOptions.plist
# Alternatively, create it dynamically in the build process