workflows:
  ios-workflow:
    name: iOS Build
    environment:
      # groups:
        # - app_store_credentials
      vars:
        BUNDLE_ID: "com.modaolah.app"
        XCODE_SCHEME: "Runner"
        
      xcode: latest
      cocoapods: default
      # Use a specific Flutter version to match your project
      flutter: "3.38.0"
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          
      - name: Generate iOS files
        script: |
          flutter precache --ios
          
      - name: Install iOS dependencies
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..
          
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ios/Runner.xcarchive/**/*
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true