workflows:
  ios-workflow:
    name: iOS TestFlight Deployment
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.soonfu.modoalah"
        APP_STORE_APPLE_ID: "e554455531gmail.com"
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0"
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Set up code signing from personal account
        script: |
          keychain initialize
          
          # Use certificates from personal account
          # Codemagic automatically uses available certificates
          # when they match the bundle ID
          
      - name: Configure Xcode project
        script: |
          cd ios
          xcode-project use-targets
          # Set the development team (get this from your Apple Developer account)
          xcode-project set-development-team "FAHAD ALHARBI"
          xcode-project update-build-settings \
            --product-bundle-identifier "$BUNDLE_ID"
          cd ..
          
      - name: Build iOS app for distribution
        script: |
          flutter build ipa --release --export-options-plist=export_options.plist
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        
      email:
        recipients:
          - mahmoud.hassan.ahmed3@gmail.com
        notify:
          success: true
          failure: true