# Codemagic YAML configuration for Flutter iOS builds
workflows:
  ios-workflow:
    name: iOS Build
    environment:
      # groups:
        # Add your environment variables here (app store credentials, etc.)
        # - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" # or your .xcworkspace
        XCODE_SCHEME: "Runner" # or your scheme
        BUNDLE_ID: "com.yourcompany.yourapp" # your app bundle ID
        FLUTTER_VERSION: "3.38.0" # specify your Flutter version
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0"
      
    scripts:
      # Set Flutter version
      - name: Set Flutter version
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      # Install Flutter dependencies
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          
      # Install iOS dependencies
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
          cd ..
          
      # Build iOS app
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true