# Codemagic YAML configuration for Flutter iOS builds
workflows:
  ios-workflow:
    name: iOS Build
    environment:
      # groups:
        # Add your environment variables here (app store credentials, etc.)
        # - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.modaolah.app" # your actual bundle ID
        FLUTTER_VERSION: "3.38.0" # or your current Flutter version
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0"
      
    scripts:
      # Set Flutter version
      - name: Set Flutter version
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      # Clean and get dependencies
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
          
      # Generate missing files if needed
      - name: Generate missing files
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs || true
          
      # Install iOS dependencies with retry
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..
          
      # Build iOS app
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true