workflows:
  ios-workflow:
    name: iOS Build & Publish
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_IDENTIFIER: "com.soonfu.modoalah"
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
      flutter: "3.27.0"
      xcode: "15.4.0"  # ✅ CRITICAL: Use the FULL version string
    scripts:
      - name: Verify Xcode version (debug step)
        script: |
          echo "Xcode version:"
          xcodebuild -version
          echo "Active Xcode path:"
          xcode-select -p

      - name: Set iOS Deployment Target
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "15.0"/' ios/Podfile || echo 'platform :ios, "15.0"' >> ios/Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\+\.[0-9]\+/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Get Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign