workflows:
  ios-workflow:
    name: iOS Build & Publish
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_IDENTIFIER: "com.soonfu.modoalah"
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
      flutter: "3.27.0"  # Use a stable version (3.38.0 doesn't exist as of 2025)
      xcode: "15.3"
    scripts:
      - name: Set iOS Deployment Target
        script: |
          # ONLY modify files - DO NOT run pod install here
          sed -i '' 's/platform :ios, .*/platform :ios, "15.0"/' ios/Podfile || echo 'platform :ios, "15.0"' >> ios/Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\+\.[0-9]\+/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Get Flutter dependencies
        script: |
          flutter clean  # Critical! Cleans old artifacts
          flutter pub get  # Generates PodHelper and fixes dependencies

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign