workflows:
  ios-workflow:
    name: iOS TestFlight Deployment
    integrations:
      app_store_connect: chat_app

    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.soonfu.modoalah"

      ios_signing:
        provisioning_profiles:
          - profile_chat_destrubutes
        certificates:
          - chat_app_distrubutes

      xcode: latest
      flutter: "3.38.0"

    scripts:

      - name: Prepare Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Initialize Codemagic keychain
        script: keychain initialize

      - name: Fetch signing files (iOS)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --platform IOS \
            --type IOS_APP_STORE \
            --create

      - name: Import signing certificate into keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles

      - name: Configure Xcode project
        script: |
          cd ios
          xcode-project use-targets
          xcode-project set-development-team "FWC7LVS9F3"
          xcode-project update-build-settings --product-bundle-identifier "$BUNDLE_ID"
          cd ..

      - name: Build IPA for TestFlight
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

      email:
        recipients:
          - mahmoud.hassan.ahmed3@gmail.com
        notify:
          success: true
          failure: true
