# codemagic.yaml
# iOS Build & Publish Workflow - Fully Fixed for Firebase Core + Xcode 15.4
# Last updated: November 14, 2025

workflows:
  ios-workflow:
    name: iOS Build & Publish
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_IDENTIFIER: "com.soonfu.modoalah"
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
      flutter: "3.38.0"
      cocoapods: default  # Ensures proper CocoaPods setup

    # Build artifacts to save
    artifacts:
      - build/ios/**/Release-iphoneos/*.ipa
      - build/ios/**/Release-iphoneos/*.app
      - build/ios/**/Release-iphoneos/*.dSYM

    # Scripts to execute in sequence
    scripts:
      # --- ENVIRONMENT SETUP ---
      - name: Display Environment Info
        script: |
          echo "=== System Information ==="
          sw_vers
          xcodebuild -version
          echo "Xcode path: $(xcode-select -p)"
          echo "Flutter version: $(flutter --version | head -1)"
          echo "CocoaPods version: $(pod --version)"
          echo "=== Environment Variables ==="
          env | grep -E 'FLUTTER|XCODE|COD' | sort

      # --- DEPENDENCY SETUP ---
      - name: Set iOS Deployment Target (ALL required locations)
        script: |
          # 1. Set Podfile deployment target
          sed -i '' 's/platform :ios, .*/platform :ios, "15.0"/' ios/Podfile || echo 'platform :ios, "15.0"' >> ios/Podfile
          
          # 2. Set Xcode project deployment target
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\+\.[0-9]\+/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' ios/Runner.xcodeproj/project.pbxproj
          
          # 3. Update AppFrameworkInfo.plist (CRITICAL for Flutter apps)
          if [ -f ios/Flutter/AppFrameworkInfo.plist ]; then
            sed -i '' 's/<key>MinimumOSVersion<\/key>.*<string>[0-9]\+\.[0-9]\+<\/string>/<key>MinimumOSVersion<\/key>\n<string>15.0<\/string>/g' ios/Flutter/AppFrameworkInfo.plist
          fi
          
          # 4. Verify all changes
          echo "=== Updated iOS Deployment Targets ==="
          echo "Podfile:"
          grep "platform :ios" ios/Podfile
          
          echo -e "\nXcode project:"
          grep -A 10 "IPHONEOS_DEPLOYMENT_TARGET" ios/Runner.xcodeproj/project.pbxproj | grep "IPHONEOS_DEPLOYMENT_TARGET"
          
          if [ -f ios/Flutter/AppFrameworkInfo.plist ]; then
            echo -e "\nAppFrameworkInfo.plist:"
            grep -A 1 "MinimumOSVersion" ios/Flutter/AppFrameworkInfo.plist
          fi

      - name: Get Flutter dependencies
        script: |
          flutter clean
          flutter pub get  # Generates PodHelper and necessary files

      - name: Update and Install CocoaPods
        script: |
          # Critical: Always run after 'flutter pub get'
          cd ios
          
          # Use system pod (no bundle exec needed since no Gemfile exists)
          pod repo update
          pod deintegrate
          pod cache clean --all
          pod install --repo-update --verbose
          
          # Verify installation
          pod outdated --allow-root
          echo "Pod installation complete"

      # --- BUILD PROCESS ---
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          
      # --- POST-BUILD VERIFICATION ---
      - name: Verify Build Artifacts
        script: |
          ls -la build/ios/iphoneos/Release-iphoneos
          file build/ios/iphoneos/Release-iphoneos/Runner.app/Runner
          
