workflows:
  ios-workflow:
    name: iOS TestFlight
    integrations:
      app_store_connect: chat_app
    environment:
      vars:
        BUNDLE_ID: "com.soonfu.modoalah"
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0"
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      - name: Clean and build
        script: |
          flutter clean
          flutter pub get
          
      - name: Configure code signing
        script: |
          cd ios
          xcode-project use-targets
          xcode-project set-development-team "YOUR_10_CHARACTER_TEAM_ID"  # Replace this
          cd ..
          
      - name: Build for TestFlight
        script: |
          flutter build ipa --release
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        
      email:
        recipients:
          - mahmoud.hassan.ahmed3@gmail.com
        notify:
          success: true
          failure: true