workflows:
  ios-workflow:
    name: iOS TestFlight
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.soonfu.modoalah"
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0"
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Build and archive for TestFlight
        script: |
          flutter build ipa --release
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        
      email:
        recipients:
          - mahmoud.hassan.ahmed3@gmail.com
        notify:
          success: true
          failure: true