workflows:
  ios-workflow:
    name: iOS Build
    environment:
      # groups:
        # - app_store_credentials
      vars:
        BUNDLE_ID: "com.soonfu.modoalah"
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0" # Use your exact Flutter version
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods
          
      - name: Get dependencies
        script: |
          flutter pub get
          
      - name: Let Flutter handle iOS setup
        script: |
          # This will regenerate proper iOS files
          flutter precache --ios
          
      - name: Build iOS app directly
        script: |
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true