workflows:
  ios-workflow:
    name: iOS TestFlight Deployment
    integrations:
      app_store_connect: chat_app
    environment:
      vars:
        BUNDLE_ID: "com.soonfu.modoalah"
        
      xcode: latest
      cocoapods: default
      flutter: "3.38.0"
      
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
          
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Set up code signing
        script: |
          keychain initialize
          
      - name: Configure Xcode project
        script: |
          cd ios
          xcode-project use-targets
          xcode-project set-development-team "FAHAD ALHARBI"
          xcode-project update-build-settings \
            --product-bundle-identifier "$BUNDLE_ID"
          cd ..
          
      - name: Build iOS app for distribution
        script: |
          flutter build ipa --release
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        
      email:
        recipients:
          - mahmoud.hassan.ahmed3@gmail.com
        notify:
          success: true
          failure: true