# Delete ALL content and replace with:
platform :ios, '15.0'
project 'Runner', 'Debug' => :debug, 'Release' => :release

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end